# Generated by Django 5.0.4 on 2024-07-03 12:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatrooms_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chatrooms',
            name='unique_chatroom_users',
        ),
        migrations.AddConstraint(
            model_name='chatrooms',
            constraint=models.UniqueConstraint(condition=models.Q(('user1__lt', models.F('user2'))), fields=('user1', 'user2'), name='unique_chat_room'),
        ),
    ]
