# Generated by Django 5.0.4 on 2024-04-23 04:59

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('designation', models.CharField(max_length=100)),
                ('profile_img', models.ImageField(null=True, upload_to='user/uploads/')),
                ('isActive', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('main.customuser',),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('published_on', models.DateField(blank=True, default=datetime.datetime.now)),
                ('thumbnail', models.ImageField(upload_to='course/uploads/')),
                ('status', models.BooleanField(default=True)),
                ('module_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.module')),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.task'),
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('designation', models.CharField(max_length=100)),
                ('linkedin_profile', models.CharField(max_length=300)),
                ('profile_img', models.ImageField(null=True, upload_to='mentor/uploads/')),
                ('isActive', models.BooleanField(default=False)),
                ('course_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.course')),
            ],
            options={
                'abstract': False,
            },
            bases=('main.customuser',),
        ),
    ]
