# Generated by Django 5.0.4 on 2024-04-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_customuser_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_active',
        ),
        migrations.AddField(
            model_name='user',
            name='isactive',
            field=models.BooleanField(default=True),
        ),
    ]
