# Generated by Django 5.0.4 on 2024-04-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_customuser_is_active_user_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
