# Generated by Django 5.0.4 on 2024-05-11 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_course_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='main.category'),
        ),
        migrations.AlterField(
            model_name='task',
            name='module',
            field=models.CharField(max_length=150),
        ),
    ]
