# Generated by Django 5.0.4 on 2024-05-11 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_course_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='published_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
