# Generated by Django 5.0.4 on 2024-05-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_course_published_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='isActive',
        ),
        migrations.RemoveField(
            model_name='user',
            name='isactive',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
