# Generated by Django 5.0.4 on 2024-06-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_mentor_isactive_remove_user_isactive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_module',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
