# Generated by Django 5.0.4 on 2024-07-30 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_mentor_degree_certificate_mentor_request_attempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='course_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.course'),
        ),
    ]
