# Generated by Django 5.0.4 on 2024-08-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_mentor_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='module',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
