# Generated by Django 5.0.4 on 2024-05-23 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0011_remove_mentor_isactive_remove_user_isactive_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrolled_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curr_module', models.CharField(max_length=100)),
                ('enroll_id', models.CharField(max_length=100)),
                ('is_completed', models.BooleanField(default=False)),
                ('certificate', models.CharField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mentor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
        migrations.CreateModel(
            name='MentorCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mentor')),
            ],
        ),
    ]
