# Generated by Django 5.0.4 on 2024-05-23 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('main', '0011_remove_mentor_isactive_remove_user_isactive_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enrolled_course',
            new_name='EnrolledCourse',
        ),
    ]
