# Generated by Django 5.0.4 on 2024-05-23 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_enrolledcourse_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrolledcourse',
            old_name='mentor',
            new_name='course',
        ),
        migrations.AlterField(
            model_name='enrolledcourse',
            name='curr_module',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
