# Generated by Django 5.0.4 on 2024-05-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_mentorcourses_course_alter_mentorcourses_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorcourses',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
