# Generated by Django 5.0.4 on 2024-05-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_mentorcourses_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RazorpayPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('provider_order_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='enrolledcourse',
            name='curr_module',
            field=models.CharField(default='module 1', max_length=100),
        ),
        migrations.AlterField(
            model_name='enrolledcourse',
            name='enroll_id',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
