# Generated by Django 5.0.4 on 2024-05-27 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_razorpaypayment_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='razorpaypayment',
            old_name='course',
            new_name='course_id',
        ),
    ]
