# Generated by Django 5.0.4 on 2024-05-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_rename_course_razorpaypayment_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorcourses',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
