# Generated by Django 5.0.4 on 2024-06-19 02:10

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_alter_mentorcourses_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledcourse',
            name='review_date',
            field=models.DateField(blank=True, default=course.models.default_review_date),
        ),
    ]
