# Generated by Django 5.0.4 on 2024-06-19 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_remove_enrolledcourse_review_date_and_more'),
        ('main', '0011_remove_mentor_isactive_remove_user_isactive_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mentor')),
            ],
        ),
    ]
