# Generated by Django 5.0.4 on 2024-06-19 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_mentortimes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentortimes',
            name='time',
            field=models.TimeField(unique=True),
        ),
    ]
