# Generated by Django 5.0.4 on 2024-06-19 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_alter_mentortimes_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledcourse',
            name='next_review_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.mentortimes'),
        ),
    ]
