# Generated by Django 5.0.4 on 2024-06-19 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_enrolledcourse_next_review_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolledcourse',
            name='next_review_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.mentortimes', unique=True),
        ),
    ]
