# Generated by Django 5.0.4 on 2024-06-21 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_reviewmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledcourse',
            name='vcall_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
