# Generated by Django 5.0.4 on 2024-06-21 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0022_alter_reviewmarks_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledcourse',
            name='total_modules',
            field=models.IntegerField(default=0),
        ),
    ]
