# Generated by Django 5.0.4 on 2024-06-21 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0023_enrolledcourse_total_modules'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrolledcourse',
            unique_together={('next_review_date', 'next_review_time')},
        ),
    ]
