# Generated by Django 5.0.4 on 2024-06-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0024_alter_enrolledcourse_unique_together'),
        ('main', '0011_remove_mentor_isactive_remove_user_isactive_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrolledcourse',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='enrolledcourse',
            constraint=models.UniqueConstraint(fields=('next_review_date', 'next_review_time'), name='unique_review_time_per_date'),
        ),
    ]
