# Generated by Django 5.0.4 on 2024-06-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0026_alter_mentortimes_time'),
        ('main', '0011_remove_mentor_isactive_remove_user_isactive_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='enrolledcourse',
            name='unique_review_time_per_date',
        ),
        migrations.AlterField(
            model_name='enrolledcourse',
            name='certificate',
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AddConstraint(
            model_name='enrolledcourse',
            constraint=models.UniqueConstraint(fields=('next_review_date',), name='unique_review_date'),
        ),
        migrations.AddConstraint(
            model_name='enrolledcourse',
            constraint=models.UniqueConstraint(fields=('next_review_time',), name='unique_review_time'),
        ),
    ]
