# Generated by Django 5.0.4 on 2024-06-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0027_remove_enrolledcourse_unique_review_time_per_date_and_more'),
        ('main', '0011_remove_mentor_isactive_remove_user_isactive_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='enrolledcourse',
            name='unique_review_date',
        ),
        migrations.RemoveConstraint(
            model_name='enrolledcourse',
            name='unique_review_time',
        ),
        migrations.AddConstraint(
            model_name='enrolledcourse',
            constraint=models.UniqueConstraint(fields=('next_review_date', 'next_review_time'), name='unique_review_time_per_date'),
        ),
    ]
