# Generated by Django 5.0.4 on 2024-06-21 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0028_remove_enrolledcourse_unique_review_date_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='enrolledcourse',
            name='unique_review_time_per_date',
        ),
    ]
