# Generated by Django 5.0.4 on 2024-06-21 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0029_remove_enrolledcourse_unique_review_time_per_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrolledcourse',
            unique_together={('next_review_date', 'next_review_time')},
        ),
    ]
