# Generated by Django 5.0.4 on 2024-06-21 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0030_alter_enrolledcourse_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolledcourse',
            name='certificate',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='enrolledcourse',
            name='next_review_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.mentortimes'),
        ),
    ]
