# Generated by Django 5.0.4 on 2024-06-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0031_alter_enrolledcourse_certificate_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrolledcourse',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='enrolledcourse',
            name='review_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='enrolledcourse',
            name='next_review_time',
        ),
    ]
