# Generated by Django 5.0.4 on 2024-06-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0033_alter_enrolledcourse_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledcourse',
            name='current_module',
            field=models.IntegerField(default=1),
        ),
    ]
