# Generated by Django 5.0.4 on 2024-07-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0034_enrolledcourse_current_module'),
        ('main', '0012_task_task_module'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrolledcourse',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='enrolledcourse',
            constraint=models.UniqueConstraint(fields=('course', 'user'), name='user_enrolled_course'),
        ),
    ]
