# Generated by Django 5.0.4 on 2024-07-13 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0035_alter_enrolledcourse_unique_together_and_more'),
        ('main', '0012_task_task_module'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='mentorcourses',
            constraint=models.UniqueConstraint(fields=('mentor', 'course'), name='unique_mentor_courses'),
        ),
    ]
