# Generated by Django 5.0.4 on 2024-07-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0036_mentorcourses_unique_mentor_courses'),
        ('main', '0012_task_task_module'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='enrolledcourse',
            constraint=models.UniqueConstraint(fields=('course', 'review_time', 'next_review_date'), name='review_time_unique'),
        ),
    ]
