# Generated by Django 5.0.4 on 2024-07-17 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0037_enrolledcourse_review_time_unique'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='enrolledcourse',
            name='review_time_unique',
        ),
    ]
