# Generated by Django 5.0.4 on 2024-07-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0038_remove_enrolledcourse_review_time_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmarks',
            name='pending_topics',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
