# Generated by Django 5.0.4 on 2024-07-17 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0039_reviewmarks_pending_topics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewmarks',
            old_name='pending_topics',
            new_name='pendings',
        ),
    ]
