# Generated by Django 5.0.4 on 2024-07-18 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0040_rename_pending_topics_reviewmarks_pendings'),
        ('main', '0012_task_task_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_transactions', to='main.user')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course.razorpaypayment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='main.user')),
            ],
        ),
    ]
