# Generated by Django 5.0.4 on 2024-07-18 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0041_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledcourse',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.razorpaypayment'),
        ),
        migrations.AddField(
            model_name='enrolledcourse',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.transaction'),
        ),
    ]
