# Generated by Django 5.0.4 on 2024-07-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0043_alter_transaction_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolledcourse',
            name='certificate',
            field=models.FileField(upload_to='pdfs/'),
        ),
    ]
