# Generated by Django 5.0.4 on 2024-07-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0044_alter_enrolledcourse_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolledcourse',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
