# Generated by Django 5.0.4 on 2024-07-24 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0046_mentortimes_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentortimes',
            name='date',
            field=models.DateField(),
        ),
    ]
