# Generated by Django 5.0.4 on 2024-07-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0048_mentortimes_booked'),
        ('main', '0012_task_task_module'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='mentortimes',
            constraint=models.UniqueConstraint(fields=('mentor', 'date', 'time', 'booked'), name='unique_time'),
        ),
    ]
