# Generated by Django 5.0.4 on 2024-07-25 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0049_mentortimes_unique_time'),
        ('main', '0012_task_task_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor_wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_count', models.IntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=10)),
                ('mentor_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mentor')),
            ],
        ),
    ]
