# Generated by Django 5.0.4 on 2024-07-26 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0050_mentor_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor_wallet',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='mentor_wallet',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentor_wallet',
            name='review_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
