# Generated by Django 5.0.4 on 2024-07-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0052_mentortransaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentor_wallet',
            old_name='mentor_wallet',
            new_name='mentor',
        ),
        migrations.AlterField(
            model_name='mentortransaction',
            name='transaction_type',
            field=models.CharField(default='BANK TRANSFER', max_length=10),
        ),
    ]
