# Generated by Django 5.0.4 on 2024-07-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0053_rename_mentor_wallet_mentor_wallet_mentor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentortransaction',
            name='transaction_type',
            field=models.CharField(default='BANK TRANSFER', max_length=15),
        ),
    ]
