# Generated by Django 5.0.4 on 2024-07-29 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0055_adminwallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor_wallet',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='mentor_wallet',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
