# Generated by Django 5.0.4 on 2024-07-29 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0056_mentor_wallet_balance_alter_mentor_wallet_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor_wallet',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10),
        ),
    ]
